version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    ignore:
      - dependency-name: "dtolnay/rust-toolchain"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: cargo
    directory: "/daemon"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: nuget
    directory: "/ui-desktop"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "*"
