[tasks.fmt-check]
workspace = false
install_crate = "rustfmt"
args = ["fmt", "--all", "--", "--check"]
command = "cargo"

[tasks.clippy]
workspace = false
install_crate = "clippy"
command = "cargo"
args = ["clippy", "--", "-D", "warnings", "-A", "unused"]

[tasks.lint-style]
workspace = false
command = "cargo"
args = ["run", "--quiet", "--package", "omnius-core-lint-style"]

[tasks.lint]
workspace = false
dependencies = ["fmt-check", "clippy", "lint-style"]

[tasks.test]
workspace = false
command = "cargo"
args = ["nextest", "run", "--all-features"]
dependencies = ["lint"]
