[core]
state_dir = "./state"

[api]
listen_addr = "127.0.0.1:5050"

[p2p]
listen_addr = "127.0.0.1:5051"
advertise_addrs = []
use_upnp = false
bootstrap_nodes = []

[logging]
level = "info"
json = false
