name: daemon-test-slim

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
      - "!main"
      - "!release/*"
    paths:
      - "daemon/**"
      - "!daemon/docs/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    working-directory: ./daemon

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Setup cargo make
        uses: davidB/rust-cargo-make@v1
        with:
          version: latest
      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2.8.0
        with:
          shared-key: lint
      - name: Lint
        run: cargo make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - name: Setup cargo make
        uses: davidB/rust-cargo-make@v1
        with:
          version: latest
      - name: Setup rust cache
        uses: Swatinem/rust-cache@v2.8.0
        with:
          shared-key: test
      - name: Test
        run: cargo test
